import type { ThemeTypes } from "@/models/ThemeType";

const BLUE_THEME: ThemeTypes = {
  name: "BLUE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#06A77D",
    secondary: "#1D90FF",
    info: "#4C9AFF",
    success: "#06A77D",
    accent: "#FF8A65",
    warning: "#FF9800",
    error: "#D32F2F",
    light: "#FFFFFF",
    lightprimary: "#E3F2FD",
    lightsecondary: "#E0F7FA",
    lightsuccess: "#E8F5E9",
    lighterror: "#FFEBEE",
    lightwarning: "#FFF3E0",
    textPrimary: "#2A3547",
    textSecondary: "#4A5568",
    borderColor: "#E0E4E8",
    inputBorder: "#CBD5E0",
    containerBg: "#FFFFFF",
    background: "#F4F7FA",
    hoverColor: "#EFF6FF",
    surface: "#FFFFFF",
    "on-surface-variant": "#F8F9FA",
    oddTableColor: "#F6F6F6",
    grey100: "#F3F4F6",
    grey200: "#A0AEC0",
    lightGrey: "#FAF9F8",
    link: "#2563EB",
    violet: "#7C3AED",

    // primary: "#1e4db7",
    // secondary: "#1a97f5",
    // info: "#539BFF",
    // success: "#05b187",
    // accent: "#FFAB91",
    // warning: "#FFAE1F",
    // error: "#e52e22",
    // light: "#ffffff",
    // lightprimary: "#e5fafb",
    // lightsecondary: "#EFaF9FF",
    // lightsuccess: "#E6FFFA",
    // lighterror: "#FDEDE8",
    // lightwarning: "#FEF5E5",
    // textPrimary: "#2A3547",
    // textSecondary: "#2A3547",
    // borderColor: "#e5eaef",
    // inputBorder: "#DFE5EF",
    // containerBg: "#ffffff",
    // background: "#f6f6f6",
    // hoverColor: "#f6f9fc",
    // surface: "#fff",
    // "on-surface-variant": "#fff",

    // oddTableColor: "#f6f6f6",
    // grey100: "#F2F6FA",
    // grey200: "#919396",
    // lightGrey: "#faf8f8",
    // link: "#0000EE",
    // violet: "#7367f0",
  },
};

const RED_THEME: ThemeTypes = {
  name: "RED_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#5e244d",
    secondary: "#ff5c8e",
    info: "#539BFF",
    success: "#05b187",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#fce6ed",
    lightsecondary: "#EDFBF7",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f6f6f6",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
    lightGrey: "#faf8f8",
    link: "#0000EE",
    violet: "#7367f0",
  },
};

const PURPLE_THEME: ThemeTypes = {
  name: "PURPLE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#402e8d",
    secondary: "#7352ff",
    info: "#539BFF",
    success: "#05b187",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#e52e22",
    lightprimary: "#F2ECF9",
    lightsecondary: "#EDF8FA",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f6f6f6",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
    lightGrey: "#faf8f8",
    link: "#0000EE",
    violet: "#7367f0",
  },
};

const GREEN_THEME: ThemeTypes = {
  name: "GREEN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#066a73",
    secondary: "#00cec3",
    info: "#539BFF",
    success: "#05b187",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#F4F9FB",
    lightsecondary: "#FAFBEF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f6f6f6",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
    lightGrey: "#faf8f8",
    link: "#0000EE",
    violet: "#7367f0",
  },
};

const INDIGO_THEME: ThemeTypes = {
  name: "INDIGO_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#11397b",
    secondary: "#1e4db7",
    info: "#539BFF",
    success: "#05b187",
    accent: "#FFAB91",
    warning: "#FFAE1F",
    error: "#FA896B",
    lightprimary: "#EBF9FA",
    lightsecondary: "#FFF5F2",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f6f6f6",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#EAEFF4",
    lightGrey: "#faf8f8",
    link: "#0000EE",
    violet: "#7367f0",
  },
};

const ORANGE_THEME: ThemeTypes = {
  name: "ORANGE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#fb9678",
    secondary: "#669961",
    dark: "#000",
    info: "#539BFF",
    success: "#05b187",
    accent: "#FFAB91",
    warning: "#fec90f",
    error: "#e52e22",
    light: "#ffffff",
    lightprimary: "#e5fafb",
    lightsecondary: "#EFF9FF",
    lightsuccess: "#E6FFFA",
    lighterror: "#FDEDE8",
    lightwarning: "#FEF5E5",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f6f6f6",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    "on-surface-variant": "#fff",
    grey100: "#F2F6FA",
    grey200: "#919396",
    lightGrey: "#faf8f8",
    link: "#0000EE",
    violet: "#7367f0",
  },
};

export {
  BLUE_THEME,
  RED_THEME,
  ORANGE_THEME,
  PURPLE_THEME,
  GREEN_THEME,
  INDIGO_THEME,
};
